
 - name: install elasticsearch
   yum:
    name: elasticsearch-7.6.2-1
    state: present

 - name: also install the drift plugin
   yum:
    name: elasticsearch-drift-plugin-7.6.2-1
    state: present

 - name: data dir
   file:
    path: /data/elastic
    owner: elasticsearch
    group: elasticsearch
    mode: 0750
    state: directory
